name: Tom Nascimento
description: 
meta_description: "Tom Nascimento"

markdown: redcarpet
pygments: true
logo: false
paginate: 15
permalink: /:title

# Details for the RSS feed generator
url:            'havoki.github.io'
author:         'Tom Nascimento'
