name: Tom Nascimento
description: Blogando meus aprendizados 
meta_description: "Tom Nascimento, Blogando meus aprendizados "

markdown: redcarpet
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'blog url'
author:         'Tom Nascimento'
