# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ewerton Nascimento
email: ewertonorg@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Entusiasta de tecnologias web, baixista e viciado em café.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ewertonorg
github_username:  ewertonorg

# Build settings
markdown: kramdown
