name: Tom Nascimento
description: Postando sobre meus aprendizados 
meta_description: "Tom Nascimento, Postando sobre meus aprendizados "

markdown: redcarpet
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'havoki.github.io'
author:         'Tom Nascimento'
